title: Data Science Study Notes - R
author: Kelin Zhong
repository:
  url: https://github.com/KelinZhong/RStudyNotes

execute:
  execute_notebooks: "force"
  timeout: 300

html:
  use_repository_button: true
  home_page_in_navbar: true

sphinx:
  config:
    html_theme: pydata_sphinx_theme
    html_theme_options:
      header_dropdown_text: "Topics"
      header_links_before_dropdown: 0
      primary_sidebar_end: ["page-toc"]
      secondary_sidebar_items: []
      collapse_navigation: false
      show_nav_level: 2
      navigation_depth: 4
      navbar_center: ["navbar-nav"]
      navbar_end: ["theme-switcher", "navbar-icon-links"]
